version: '3.4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgresql-midpoint:
    image: postgres:13-alpine
    container_name: book-postgresql-midpoint-chapter-2
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
      - POSTGRES_USER=midpoint
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 19911:19911
    networks:
      - net
    secrets:
      - mp_database_password.txt
    volumes:
      - pg-midpoint_data:/var/lib/postgresql/data

  postgresql-crm:
    image: postgres:13-alpine
    container_name: book-postgresql-crm-chapter-2
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=crm
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 15432:19911
    networks:
      - net
    volumes:
      - pg-crm_data:/var/lib/postgresql/data
      - ./book-chapter-common/container-book-postgres-crm_files:/docker-entrypoint-initdb.d/:ro

  ldap:
    image: osixia/openldap:stable
    container_name: book-ldap-chapter-2
    entrypoint: [ "/container/tool/run", "--copy-service" ]
    ports:
      - "10389:389"
    environment:
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_TLS=false
    networks:
      - net
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
      - ./book-chapter-common/container-book-ldap_files:/container/service/slapd/assets/config/bootstrap/ldif/custom/:ro

  midpoint:
    image: evolveum/midpoint:latest
    container_name: book-midpoint-chapter-2
    ports:
      - "42673:42673"
    environment:
      - MP_ENTRY_POINT=/opt/midpoint-dirs-docker-entrypoint
      - REPO_DATABASE_TYPE=postgresql
      - REPO_HOST=book-postgresql-midpoint-chapter-2
      - REPO_DATABASE=midpoint
      - REPO_USER=midpoint
      - REPO_PASSWORD_FILE=/run/secrets/mp_database_password.txt
      - MP_KEYSTORE_PASSWORD_FILE=/run/secrets/mp_keystore_password.txt
    networks:
      - net
    secrets:
      - mp_database_password.txt
      - mp_keystore_password.txt
    volumes:
      - midpoint_home:/opt/midpoint/var
      - ./book-chapter-2/container-book-midpoint_files:/opt/midpoint-dirs-docker-entrypoint/:ro
      - ./book/book-chapter-2/container-book-midpoint_files/resources:/resources
    depends_on:
      - ldap
      - postgresql-crm
      - postgresql-midpoint

networks:
  net:
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./book-chapter-common/configs-and-secrets/database_password.txt
  mp_keystore_password.txt:
    file: ./book-chapter-common/configs-and-secrets/keystore_password.txt

volumes:
  midpoint_home:
    name: book-midpoint_home-chapter-2
  ldap_conf:
    name: book-ldap_conf-chapter-2
  ldap_data:
    name: book-ldap_data-chapter-2
  pg-midpoint_data:
    name: book-postgresql-midpoint_data-chapter-2
  pg-crm_data:
    name: book-postgresql-crm_data-chapter-2